resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git
      ref: refs/heads/main # pin to stable version of the repo

trigger:
  branches:
    include:
      - main
      - develop

pr: none

pool: ara-devops-agents-01
extends:
  template: build_and_deploy.yaml@templates
  parameters:
    appName: |
      my cool app 
      hej hej
    azureSubscription: "johan-testing-sc"
    runForPython: true
    useGitVersion: false
    artifactFeeds: "azure-ci-cd-playground/ARA-PLAYGROUND-FEED"
    useTerraform: false
