# File: azure-pipelines.yml
variables: # Global variables
  - template: templates/commonVars.yml # Template reference
    parameters:
      app: "azure-devops"
pool:
  vmImage: ubuntu-latest

trigger:
  - main

jobs:
  - template: templates/my-cool-pipline.yml # Template reference
    parameters:
      name: Linux
      vmImage: "ubuntu-latest"
