resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git
      ref: refs/heads/main # pin to stable version of the repo

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pr:
  - main

variables:
  - template: variables/commonVariables.yaml@templates
    parameters:
      appName: "Johan-Test"
  - name: deploy
    ${{ if in(variables['Build.SourceBranch'], 'refs/heads/feature/*') }}:
      value: false
    ${{ elseif eq(variables['Build.Reason'], 'PullRequest') }}:
      value: false
    ${{ else }}:
      value: true
  - name: testOnly
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: true
    ${{else}}:
      value: false

name: $(appName)-$(environment).$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-latest
stages:
  #- template: blocks/gitversionStage.yaml@templates
  - stage: pytest
    displayName: Pytest
    jobs:
      - job: pytest
        steps:
          - script: echo "Placeholder for pytest"
          - script: echo $(Build.Reason)
  - stage: buildPush
    dependsOn: pytest
    condition: or(eq(dependencies.precheck.outputs['check.CheckChanges.runBuild'], 'true'), eq(variables['Build.Reason'], 'Manual'))
    displayName: Build and Push
    jobs:
      - job: buildPush
        steps:
          - template: steps/pipAuthenticate.yaml@templates
            parameters:
              onlyAddExtraIndex: true
          - template: steps/dockerBuild.yaml@templates
            parameters:
              buildArguments: --build-arg INDEX_URL=$(PIP_EXTRA_INDEX_URL)
