resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

trigger:
  branches:
    include:
      - main
      - develop

pr: none

pool:
  vmImage: ubuntu-latest
# extends:
#   template: build_and_deploy.yaml@templates
#   parameters:
#     appName: "my-app"

steps:
  - bash: |
      set -a
      source version.env
      set +a
    displayName: "Load version.env"
  - bash: env
    displayName: "Print env"
  - bash: echo $(TESTVERSION)
    displayName: "Print TESTVERSION"
