resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

trigger:
  branches:
    include:
      - main
      - develop

pr: none

pool:
  vmImage: ubuntu-latest

extends:
  template: build_and_deploy@templates
  parameters:
    appName: "my-app"
