resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git
pool:
  vmImage: ubuntu-latest

stages:
  - template: terraform.yaml@templates
