# File: azure-pipelines.yml
variables: # Global variables
  - template: templates/commonVars.yml # Template reference
    parameters:
      app: "azure-devops"
pool:
  vmImage: ubuntu-latest

trigger:
  - main

extends:
  template: templates/simple-param.yml
  parameters:
    yesNo: true # set to a non-boolean value to have the build fail

extends:
  template: templates/my-cool-pipeline.yml
