resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Install
    jobs:
      - job: npminstall
        steps:
          - task: Npm@1
            inputs:
              command: "install"
  - template: terraform.yaml@templates
