trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

variables:
  - template: commonVariables.yaml@templates
  - name: my_sweet_variable
    value: "This is my sweet variable"

stages:
  - stage: gitversion
    jobs:
      - job: gitversion
        steps:
          - checkout: self
            fetchDepth: 0
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@0
            name: version # id to later be referenced
            inputs:
              updateAssemblyInfo: true # will update the AssemblyInfo.cs file
              updateAssemblyInfoFilename: "**/AssemblyInfo.cs" # will update all AssemblyInfo.cs files in the repo
            displayName: Use GitVersion
  - template: precheck.yaml@templates
  - template: terraform.yaml@templates
