resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git
      ref: refs/heads/main # pin to stable version of the repo

trigger:
  branches:
    include:
      - main
      - develop

pr: none

variables:
  # - template: variables/commonVariables.yaml@templates
  #   parameters:
  #     appName: "Johan-Test"
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    why: pr
  ${{ elseif eq(variables['Build.Reason'], 'Manual' ) }}:
    why: manual
  ${{ elseif eq(variables['Build.Reason'], 'IndividualCI' ) }}:
    why: indivci
  ${{ else }}:
    why: other

name: $(SourceBranchName)_$(why).$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-latest
stages:
  #- template: blocks/gitversionStage.yaml@templates
  - stage: printStuff
    jobs:
      - job: printStuff
        steps:
          - script: echo "Hello worldd"
          - script: echo "Build number $(Build.BuildNumber)"
