# File: azure-pipelines.yml

pool:
  vmImage: ubuntu-latest

trigger:
  - main

extends:
  template: templates/simple-param.yml
  parameters:
    yesNo: false # set to a non-boolean value to have the build fail
