resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

trigger:
  branches:
    include:
      - main
      - develop

pr: none

pool:
  vmImage: ubuntu-latest
# extends:
#   template: build_and_deploy.yaml@templates
#   parameters:
#     appName: "my-app"

steps:
  - bash: |
      echo "##vso[task.setvariable variable=TESTVERSION]$(cat version.env)"
    displayName: "Load version.env"
  - bash: env
    displayName: "Print env"
  - bash: echo "$(TESTVERSION)"
    displayName: "Print TESTVERSION"
  - task: AzureFileCopy@4
    inputs:
      SourcePath: "version.env"
      azureSubscription: "johan-testing-sc"
      Destination: "AzureBlob"
      storage: "arajohantesting"
      ContainerName: "blobs"
      BlobPrefix: ""
    name: AzureFileCopy

  - script: |
      echo $(AzureFileCopy.StorageContainerUri)
      echo $(AzureFileCopy.StorageContainerSasToken)
