resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

pool:
  vmImage: "ubuntu-latest"

trigger:
  - main

stages:
  - template: terraform.yaml@templates
    parameters:
      environment: staging
      serviceName: johan-devops-test
  - stage: deploy
    displayName: Deploy
    dependsOn: terraform
    condition: succeeded('terraform')
    jobs:
      - job: deploy
        displayName: Deploy
        steps:
          - script: echo "Deploying"
