# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: johanalmquist/azure-devops-templates

variables: # Global variables
  - template: commonVariables.yml@templates
    parameters:
      app: "azure-devops"
pool:
  vmImage: ubuntu-latest

trigger:
  - main

jobs:
  - job: build
    steps:
      - script: echo "Deploy $(app)"
