# File: azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      name: johan-azure/johan-azure
      type: git

variables: # Global variables
  - template: commonVariables.yml@templates
    parameters:
      app: "azure-devops"
pool:
  vmImage: ubuntu-latest

trigger:
  - main

jobs:
  - template: npm/npm-with-params.yml@templates # Template reference
    parameters:
      name: Linux
      vmImage: "ubuntu-latest"

  - template: npm/npm-with-params.yml@templates # Template reference
    parameters:
      name: Windows
      vmImage: "windows-latest"
