trigger:
  branches:
    include:
      - main
      - develop

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

steps:
  - task: DownloadBuildArtifacts@1
    displayName: Download Plan Atrifact
    inputs:
      artifactName: "2124-api-people-billing-staging-tfplan"
# variables:
#   - template: commonVariables.yaml@templates
#   - name: my_sweet_variable
#     value: "This is my sweet variable"
#   - name: app
#     value: "my-app"
#   - name: test_var
#     value: true

# stages:
#   - template: precheck.yaml@templates
#   - template: terraform.yaml@templates
#   - template: dockerbuild.yaml@templates
#   - template: k8s.yaml@templates
