resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git
      ref: refs/heads/main # pin to stable version of the repo

trigger:
  branches:
    include:
      - main
      - develop

pr: none

variables:
  - template: variables/commonVariables.yml@templates
    parameters:
      appName: "Johan-Test"

name: $(appName).$(environment).$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-latest
stages:
  - stage: printStuff
    jobs:
      - job: printStuff
        steps:
          - script: echo "Hello world"
          - script: echo "Build number $(Build.BuildNumber)"
