resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

trigger:
  branches:
    include:
      - main
      - develop

pr: none

extends:
  template: my-template.yaml@templates
