trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

variables:
  - template: commonVariables.yaml@templates
  - name: my_sweet_variable
    value: "This is my sweet variable"

stages:
  - template: precheck.yaml@templates
  - template: terraform.yaml@templates
