resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - template: precheck.yaml@templates
  - template: terraform.yaml@templates
