resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git
      ref: refs/heads/main # pin to stable version of the repo

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pr:
  - main

variables:
  - template: variables/commonVariables.yaml@templates
    parameters:
      appName: "Johan-Test"
  - name: deploy
    ${{ if in(variables['Build.SourceBranch'], 'refs/heads/feature/*') }}:
      value: false
    ${{ elseif eq(variables['Build.Reason'], 'PullRequest') }}:
      value: false
    ${{ else }}:
      value: true
  - name: testOnly
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: true
    ${{else}}:
      value: false

name: $(appName)-$(environment).$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-latest
stages:
  #- template: blocks/gitversionStage.yaml@templates
  - stage: buildPush
    displayName: Build and Push
    jobs:
      - template: steps/pipAuthenticate.yaml@templates
        paramters:
          onlyAddExtraIndex: true
      - template: jobs/docker.yaml@templates
        paramters:
          buildArguments: --build-arg INDEX_URL=$(PIP_EXTRA_INDEX_URL)
