resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git
      ref: refs/branches/main

trigger:
  branches:
    include:
      - main
      - develop

pr: none

pool: ara-devops-agents-01
extends:
  template: build_and_deploy.yaml@templates
  parameters:
    appName: "johans-test-app"
    azureSubscription: "johan-testing-sc"
