resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

variables:
  - name: my_sweet_variable
    value: "This is my sweet variable"

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - template: precheck.yaml@templates
  - template: terraform.yaml@templates
