pool:
  vmImage: ubuntu-latest

stages:
  - stage: pre
    jobs:
      - job: check
        displayName: Check changed files
        steps:
          - checkout: self
            fetchDepth: "0"
          - task: ChangedFiles@1.2.3
            name: CheckChanges
            inputs:
              verbose: true
              rules: |
                [TerraformChanged]
                terraform/*.tf

                [FooChanged]
                foo/**

  - stage: terra_has_changed
    dependsOn: ["pre"]
    displayName: This stage runs only when the `TerraformChanged` variable is true
    condition: eq(dependencies.pre.outputs['check.CheckChanges.TerraformChanged'], 'true')
    jobs:
      - job: run
        steps:
          - script: echo "TerraformChanged has changed"

  - stage: foo_has_changed
    dependsOn: ["pre"]
    displayName: This stage runs only when the `FooChanged` variable is true
    condition: eq(dependencies.pre.outputs['check.CheckChanges.FooChanged'], 'true')
    jobs:
      - job: run
        steps:
          - script: echo "Foo has changed"

  - stage: stage_with_conditional_job
    dependsOn: ["pre"]
    displayName: The stage always runs but contains a job that runs only when `FooChanged` is true
    jobs:
      - job: job_when_foo_has_changed
        displayName: This job runs only when `FooChanged` is true
        condition: eq(stageDependencies.pre.check.outputs['CheckChanges.FooChanged'], 'true')
        steps:
          - script: echo "Foo has changed"
