trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

variables:
  - template: commonVariables.yaml@templates
  - name: my_sweet_variable
    value: "This is my sweet variable"

stages:
  - stage: gitversion
    jobs:
      - job: gitversion
        steps:
          - checkout: self
            fetchDepth: 0
          - task: gitversion@5
            displayName: US GitVersion
            inputs:
              versionSpec: "5.x"
              updateAssemblyInfo: true
              updateAssemblyInfoFilename: "**/AssemblyInfo.*"
  - template: precheck.yaml@templates
  - template: terraform.yaml@templates
