# File: azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      name: johanalmquist/azure-devops-templates
      type: github
      endpoint: joh-github
      ref: refs/heads/main
      folder: templates

variables: # Global variables
  - template: commonVariables.yml@templates
    parameters:
      app: "azure-devops"
pool:
  vmImage: ubuntu-latest

trigger:
  - main

jobs:
  - template: npm/npm-with-params.yml@templates # Template reference
    parameters:
      name: Linux
      vmImage: "ubuntu-latest"

  - template: npm/npm-with-params.yml@templates # Template reference
    parameters:
      name: Windows
      vmImage: "windows-latest"
