trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      name: Aranya-Devops-Templates/Aranya-Devops-Templates
      type: git

variables:
  - template: commonVariables.yaml@templates
  - name: my_sweet_variable
    value: "This is my sweet variable"

stages:
  - stage: gitversion
    jobs:
      - job: gitversion
        steps:
          - checkout: self
            fetchDepth: 0
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@0
            name: version # id to later be referenced
            displayName: Use GitVersion
          - task: CmdLine@2
            displayName: Init git global config
            inputs:
              script: |
                git config --global user.email "devops@aranya.se"
                git config --global user.name "CI / CD Pipeline"
          - task: CmdLine@2
            displayName: Create Git tag for current version
            inputs:
              script: |
                git tag -a $(GitVersion.SemVer) -m "Tagged version $(GitVersion.SemVer)"
                git push origin $(GitVersion.SemVer)
  - template: precheck.yaml@templates
  - template: terraform.yaml@templates
