apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base"

patches:
  - path: "ingress.yaml"
  - path: "deployment.yaml"

images:
  - name: aranyaprivate.azurecr.io/johans-test-app
    newTag: staging

configMapGenerator:
  - name: johans-test-app
    behavior: merge
    envs:
      - "config.env"
